name: xeus-kernel
channels:
  - https://repo.prefix.dev/ck-emscripten-forge-dev
  - https://repo.prefix.dev/emscripten-forge-4x
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-r>=0.8.1
  # -r-tidyverse is not available yet due to upper pin on r-base, and
  # older r-base versions are not available on emscripten-forge, so we
  # install some of the tidyverse packages individually (except for
  # r-lubridate)
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-purrr
  - r-tibble
  - r-stringr
  - r-forcats
  - r-coursekata
  - r-neuralnet
